### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by Aryan-Chharia** [shrawani21/gamer_21#11]
I suggest adding a code of conduct to this repo. Can you assign this to me under GSSoC'24?

**Comment by MrCodYrohit** [comment]
👋 Hello there! As a contributor to GSSoC 2024, I'm eager to embark on my journey into the realm of open-source contributions. I'm keen to revamp your project's Code of Conduct section, infusing it with user-friendliness and engagement. Would you kindly assign me this task? Also, could you specify the appropriate level for labeling purposes? Thanks for your time! 🚀

**Comment by Pranjalll01** [comment]
Hey @MrCodYrohit 
Pranjal Kushwaha here , Contributor@GSSoc'24
repo currently lacks a CODE_OF_CONDUCT.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CODE_OF_CONDUCT.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

could you please assign this to me ?

**Comment by MrCodYrohit** [comment]
> Hey @MrCodYrohit Pranjal Kushwaha here , Contributor@GSSoc'24 repo currently lacks a CODE_OF_CONDUCT.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CODE_OF_CONDUCT.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.
> 
> could you please assign this to me ?

I am not a mentor.

**Comment by Priyanshu2631** [comment]
Please assign this issue to me

**Comment by 2004khushig** [comment]
Hi! Khushi this side. I believe that before getting started with any project, we should be thorough with the code of conduction of the same. There are certain factors that are to be met and certain parameters it should consider. Therefore, I would like to add Code Of Conduct to this project. Please assign this to me.
Thanks!

**Comment by Tejasri-Pendota** [comment]
I would like to contribute to the project by adding code of conduct. This will explain its purpose and key guidelines for fostering a welcoming and inclusive community. As a beginner eager to learn and contribute, I am confident this task suits my skills. Could you please assign this issue to me under the label Gssoc?
