### ISSUE TITLE
Add Documentation to your Code

### ISSUE THREAD

**Issue by PilotAxis** [shrawani21/gamer_21#16]
Hi @shrawani21 I would like to add documentation to your code, please assign this issue to me

**Comment by snehatungana** [comment]
I would like to work on this issue for GSSoC 24, kindly assign this issue to me.

**Comment by Sandhyarani23** [comment]
I can do the documentation.
the outline covers the key aspects of documentation, including installation/setup, usage ,  examples, troubleshooting, feedback, version history, and conclusion. Each section is designed to be clear, concise, and easy to understand, with a focus on providing value to the user. Please assign this task to me under GSSOC's24

**Comment by Messycodess** [comment]
hey project manager ..kindly add the GSSOC'24 labels so that our contributions can be tracked

**Comment by arunabhshikhar** [comment]
I would like to work on this issue, kindly assign me this issue. 
Also I would like to request that please add the GSSOC'24 labels and respective difficullty levels.

**Comment by Akshitha28112004** [comment]
Hey, I already have the documentation file for this ready. I hope you like it. Please assign me this work.

**Comment by Tejasri-Pendota** [comment]
as a begginer ,this issue will greatly help me knowing how everthing works . I would like to contribute by adding documentation to your code, would u add the label of GSSOC'24 and assign this to me.
