### ISSUE TITLE
Bugs and it doesn't show current player's turn

### ISSUE THREAD

**Issue by rahilmavani** [shrawani21/gamer_21#35]
The current version of code have bugs, to ensure proper working it needs some work. It doesn't show which player's turn it is, so need to make sure it shows that.

I have requested a pull request with solution for the same.

**Comment by Cralsic123** [comment]
@rahilmavani Would like to solve this issue
I am good at python, if you need assurance look into my profile. 
Please assign me as GSSOC contributor.

**Comment by ShravaniPathak** [comment]
I would like to work on this issue. Please assign this task to me
