### ISSUE TITLE
Missing CONTRIBUTING.md file in repository 

### ISSUE THREAD

**Issue by Braj-01** [shrawani21/gamer_21#41]
The repository currently lacks a CONTRIBUTING.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CONTRIBUTING.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

Could you please assign this issue to me under GSSOC 24.

**Comment by Braj-01** [comment]
Pls assign me this task.

**Comment by Braj-01** [comment]
@Priyanshu2631 pls add label

**Comment by Braj-01** [comment]
Pls add label on it.

**Comment by Chanc2206** [comment]
missing of package.json file

**Comment by Braj-01** [comment]
Ok, I will check.

**Comment by Braj-01** [comment]
I've made changes pls check it out.

**Comment by aasthakourav20** [comment]
Hey @shrawani21 , this issue is still open .If not worked upon kindly assign it to me , I will make changes

**Comment by suhanipaliwal** [comment]
Duplicate issue. It was already raised #24
