### ISSUE TITLE
The Game Over and result is not visible properly 

### ISSUE THREAD

**Issue by khushi463-tyagi** [shrawani21/gamer_21#80]
The Game Over and final result is not visible properly and are difficult to read.

![Screenshot 2024-05-21 232406](https://github.com/shrawani21/gamer_21/assets/66127538/7db3ab12-105d-43fd-abe2-53c4678c012d)

As a GSSOC contributor, I want to update this issue and contribute to this project.
Please assign this issue

**Comment by shrawani21** [comment]
@khushi463-tyagi

**Comment by khushi463-tyagi** [comment]
@shrawani21 hello pa, did you assign this issue to me? but I am not able to see my name under assignes

**Comment by aasthagupta1** [comment]
I would like to work on this issue ,Please assign this issue to me @shrawani21

**Comment by khushi463-tyagi** [comment]
@Priyanshu2631 thanks for assigning this issue I will start working on this

**Comment by khushi463-tyagi** [comment]
@Priyanshu2631 Hello, I have raised the pull request could you please check it, and if any suggestions are needed let me know

**Comment by shrawani21** [comment]
@khushi463-tyagi
